#!/usr/bin/env python3
"""Put a written executive synthesis into an already generated report.

    python3 inject_narrative.py report.html synthesis.md --who "Claude, via the skill" [--template ...]

The report is regenerated from its own embedded data, so nothing is recomputed
and the figures cannot drift from what the synthesis was written against. The
text is inserted under its own label, with who wrote it and when, so a reader
never mistakes prose for measurement.

Paragraphs are blank-line separated. No HTML is interpreted: what you write is
what appears, escaped.
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime

import report_html

MARK = re.compile(r"const DATA = (\{.*?\});\n", re.S)


def extract(html: str) -> dict:
    m = MARK.search(html)
    if not m:
        raise SystemExit("No embedded data found: is this a report generated by review.py?")
    return json.loads(m.group(1).replace("<\\/", "</"))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("report")
    ap.add_argument("text", help="plain text or Markdown-ish file; paragraphs separated by blank lines")
    ap.add_argument("--who", default="the reviewer")
    ap.add_argument("--template")
    ap.add_argument("-o", "--out", help="write here instead of overwriting the report")
    args = ap.parse_args()

    with open(args.report, encoding="utf-8") as fh:
        payload = extract(fh.read())
    with open(args.text, encoding="utf-8") as fh:
        text = fh.read().strip()
    if not text:
        raise SystemExit("The synthesis file is empty.")
    lang = payload.get("lang", "en")
    when = datetime.now().strftime("%d/%m/%Y %H:%M" if lang == "pt" else "%Y-%m-%d %H:%M")
    payload["narrative"] = {"text": text, "who": args.who, "when": when}
    out = args.out or args.report
    report_html.write(payload, out, args.template)
    print(out)


if __name__ == "__main__":
    main()
